run:
  modules-download-mode: vendor
  skip-dirs:
    - .build
    - .github
    - benchmarks
    - bin
    - configs

linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - maligned
    - misspell
    - prealloc
    - stylecheck
    - unparam
  disable:
    - deadcode
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lukasmalkmus/spl
  govet:
    check-shadowing: true
