run:
  modules-download-mode: vendor

linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - maligned
    - misspell
    - prealloc
    - stylecheck
    # - unparam

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lukasmalkmus/spl
  govet:
    check-shadowing: true
